AWSTemplateFormatVersion: "2010-09-09"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t3.micro
      ImageId: ami-0f5ee92e2d63afc18
      Tags:
        - Key: Name
          Value: MyFirstEC2Instance-github